// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECPZ_fbW_xIcwx_WdiC25onum1jIL4k0',
    appId: '1:500210534719:web:79f96e35ac61b680556b8a',
    messagingSenderId: '500210534719',
    projectId: 'rehabspace-c9289',
    authDomain: 'rehabspace-c9289.firebaseapp.com',
    storageBucket: 'rehabspace-c9289.firebasestorage.app',
    measurementId: 'G-3S7ESKHEWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU70ftVml1yldI7xJmlzuQoo0Q3D77ENM',
    appId: '1:500210534719:android:68c330a40229c258556b8a',
    messagingSenderId: '500210534719',
    projectId: 'rehabspace-c9289',
    storageBucket: 'rehabspace-c9289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXzjd9BSDcMiqnJyrl5zQYzM23fYrPekg',
    appId: '1:289551440398:ios:54f91c84bc4fa63b67fa5f',
    messagingSenderId: '289551440398',
    projectId: 'rehabspace-623cc',
    storageBucket: 'rehabspace-623cc.firebasestorage.app',
    iosBundleId: 'com.example.rehabspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXzjd9BSDcMiqnJyrl5zQYzM23fYrPekg',
    appId: '1:289551440398:ios:54f91c84bc4fa63b67fa5f',
    messagingSenderId: '289551440398',
    projectId: 'rehabspace-623cc',
    storageBucket: 'rehabspace-623cc.firebasestorage.app',
    iosBundleId: 'com.example.rehabspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd-jd-TGOFsK6ZijCoVlP5KTw2I3FBRr0',
    appId: '1:289551440398:web:d25c6730e8b682d767fa5f',
    messagingSenderId: '289551440398',
    projectId: 'rehabspace-623cc',
    authDomain: 'rehabspace-623cc.firebaseapp.com',
    storageBucket: 'rehabspace-623cc.firebasestorage.app',
    measurementId: 'G-M3BL8YPF94',
  );
}
